version: "3.9"

services:
  dbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: dbeaver-cloud
    environment:
      - VIRTUAL_HOST=${DOMAIN}
      - VIRTUAL_PORT=8978
    env_file:
      - ./.env
    ports:
      - 8979:8978
    volumes:
      - ./workspace:/opt/cloudbeaver/workspace
    networks:
      - docker-net
    deploy:
      resources:
        limits:
          cpus: ${LIMIT_CPU}
          memory: ${LIMIT_MEM}

networks:
  docker-net:
    external: ${NET_EXTERNAL}


